all:
	pdflatex chacon-ieeecyb-19.tex
	bibtex chacon-ieeecyb-19
	pdflatex chacon-ieeecyb-19.tex
	pdflatex chacon-ieeecyb-19.tex
clean:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~
	
cleanall:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~ chacon-ieeecyb-19.pdf *.ps 
