all:
	pdflatex chacon-ieeecyb-19-sm.tex
	bibtex chacon-ieeecyb-19-sm
	pdflatex chacon-ieeecyb-19-sm.tex
	pdflatex chacon-ieeecyb-19-sm.tex
clean:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~
	
cleanall:
	rm -f *.log *.dvi *.aux *.bbl *.blg *~ chacon-ieeetec-19-sm.pdf *.ps 
